after_success:
- chmod -R 777 ./travis/after_success.sh
- ./travis/after_success.sh
language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- echo "MAVEN_OPTS='-Dlicense.skip=true'" > ~/.mavenrc
install:
- jdk_switcher use oraclejdk8
- chmod -R 777 ./travis/install.sh
- ./travis/install.sh
- jdk_switcher use ${TRAVIS_JDK_VERSION}
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
